# Generated by Django 5.0.1 on 2024-01-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=10, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=10, verbose_name='Last Name')),
                ('position', models.CharField(help_text='Enter your position', max_length=10, verbose_name='Position')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter game's title", max_length=10, verbose_name='Title')),
                ('genre', models.CharField(help_text="Enter game's genre", max_length=10, verbose_name='Genre')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter article's title", max_length=10, verbose_name='Title')),
                ('author', models.ForeignKey(help_text="Enter article's author", on_delete=django.db.models.deletion.CASCADE, to='pls_w.employee', verbose_name="Article's Author")),
                ('game', models.ForeignKey(help_text='Enter game this article covers', on_delete=django.db.models.deletion.CASCADE, to='pls_w.game', verbose_name='Game')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
