# Generated by Django 5.0.1 on 2024-02-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0002_alter_article_title_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': "game's genres",
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('short_desc', models.CharField(max_length=10, verbose_name='Short Description')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default='default', help_text="Enter game's genre", on_delete=django.db.models.deletion.CASCADE, to='pls_w.gamegenre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='gamegenre',
            name='genre_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_genre', to='pls_w.genre', verbose_name='Main Genre'),
        ),
        migrations.AddField(
            model_name='gamegenre',
            name='genre_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genre', to='pls_w.genre', verbose_name='Sub Genre'),
        ),
    ]
