# Generated by Django 5.0.1 on 2024-02-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0004_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='genre_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mg', to='pls_w.genre', verbose_name='Main Genre'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='genre_sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sg', to='pls_w.genre', verbose_name='Sub Genre'),
        ),
    ]
