# Generated by Django 5.0.1 on 2024-02-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0006_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(help_text='Enter genre of this game', on_delete=django.db.models.deletion.CASCADE, to='pls_w.genre', verbose_name='Genre'),
        ),
        migrations.DeleteModel(
            name='GameGenre',
        ),
    ]
