# Generated by Django 5.0.1 on 2024-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0007_alter_game_genre_delete_gamegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, verbose_name=''),
        ),
    ]
