# Generated by Django 5.0.1 on 2024-02-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0008_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
