# Generated by Django 5.0.1 on 2024-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0009_remove_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Enter text', max_length=1000, null=True, verbose_name='Content'),
        ),
    ]
