# Generated by Django 4.2.10 on 2024-02-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls_w', '0010_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Enter text', null=True, verbose_name='Content'),
        ),
    ]
